// src/component/header/Header.svelte
<script>
  import { Header } from "./header";

  let data;
  const setData = (newData) => {data = newData};
  const header = new Header(setData);
</script>

<style>@import url("./header.css");</style>


<!-- svelte-ignore component-name-lowercase -->
<header class="header flex-i-col" style={`zoom: ${data.zoom}`}>
  <div class="flex-i-col">
    <img
      class="ffaee-logo"
      src={data.imageMap.ffaeeLogo}
      alt="Final Fight Anniversary Edition Editor (CPS1)"
    />
    <img src={data.imageMap.portraitGuy} alt="Guy" />
    <img src={data.imageMap.portraitCody} alt="Cody" />
    <img src={data.imageMap.portraitHaggar} alt="Haggar" />
  </div>
</header>

// src/components/header/HeaderComponent.jsx
import React from 'react';

import imageMap from '../../data/ImageMap';

import "./Header.css";


const HeaderComponent = (props) =>
{
  let logoTitle =
      "Final Fight Anniversary Edition Editor";
      
  return (
    <header
      className="header colLinedFlex"
      style={{zoom: props.zoom}}
    >
      <div className="colLinedFlex">
        <img
          className="ffaeeLogo"
          src={imageMap.ffaeeLogo}
          title={logoTitle}
        />
        <div className="colLinedFlex">
          <img
            src={imageMap.portraitGuy}
            title="Guy"
          />
          <img
            src={imageMap.portraitCody}
            title="Cody"
          />
          <img
            src={imageMap.portraitHaggar}
            title="Haggar"
          />
        </div>
      </div>
    </header>
  );
}


export default HeaderComponent;
