// src/component/footer/Footer.svelte
<script>
  import { Footer } from "./footer";

  let data;
  const setData = (newData) => {data = newData}
  const footer = new Footer(setData);
</script>

<style>@import url("./footer.css");</style>


<!-- svelte-ignore component-name-lowercase -->
<footer id="footer" class="footer" style={`zoom: ${data.zoom}`}>
  <div class="flex-i-col">
    <a href="https://github.com/GameHackFan/ffaee" target="_blank">
      Source Code
    </a>
    <span>{data.appVersion}</span>
  </div>
</footer>

// src/components/footer/FooterComponent.jsx
import React from 'react';

import "./Footer.css";


const FooterComponent = (props) =>
{
	let appVersion = "Version 0.4, \u00A9 2021";

	return (
		<footer
			id="footer"
			className="footer colLinedFlex"
			style={{zoom: props.zoom}}
		>
			<div className="colLinedFlex">
				<a href="https://github.com/GameHackFan/ffaee" target="_blank">
					Source Code
				</a>
				<label>{appVersion}</label>
			</div>
		</footer>
	);
}


export default FooterComponent;
